---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gymhive-secret-sync
  namespace: gymhive
  labels:
    app: gymhive-secret-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gymhive-secret-sync
  template:
    metadata:
      labels:
        app: gymhive-secret-sync
    spec:
      serviceAccountName: gymhive-ksa
      containers:
      - name: pause
        image: registry.k8s.io/pause:3.10
        volumeMounts:
        - name: secrets-store-inline
          mountPath: /var/secrets
          readOnly: true
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store-gke.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: gymhive-gcp-secrets
