---
apiVersion: v1
kind: Namespace
metadata:
  name: gymhive
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gymhive-ksa
  namespace: gymhive
  annotations:
    iam.gke.io/gcp-service-account: gymhive-gke-sa@gymhive.iam.gserviceaccount.com
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: gymhive-gcp-secrets
  namespace: gymhive
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/gymhive/secrets/jwt-secret/versions/latest"
        fileName: "jwt-secret"
      - resourceName: "projects/gymhive/secrets/password-pepper/versions/latest"
        fileName: "password-pepper"
      - resourceName: "projects/gymhive/secrets/mysql-root-password/versions/latest"
        fileName: "mysql-root-password"
      - resourceName: "projects/gymhive/secrets/rabbitmq-password/versions/latest"
        fileName: "rabbitmq-password"
      - resourceName: "projects/gymhive/secrets/mongodb-connection-string/versions/latest"
        fileName: "mongodb-connection-string"
      - resourceName: "projects/gymhive/secrets/auth-db-connection-string/versions/latest"
        fileName: "auth-db-connection-string"
      - resourceName: "projects/gymhive/secrets/gym-db-connection-string/versions/latest"
        fileName: "gym-db-connection-string"
      - resourceName: "projects/gymhive/secrets/notifications-db-connection-string/versions/latest"
        fileName: "notifications-db-connection-string"
      - resourceName: "projects/gymhive/secrets/workout-db-connection-string/versions/latest"
        fileName: "workout-db-connection-string"
  secretObjects:
  - secretName: gymhive-jwt-secret
    type: Opaque
    data:
    - objectName: jwt-secret
      key: JWT_SECRET
  - secretName: gymhive-password-pepper
    type: Opaque
    data:
    - objectName: password-pepper
      key: PASSWORD_PEPPER
  - secretName: gymhive-mysql-password
    type: Opaque
    data:
    - objectName: mysql-root-password
      key: MYSQL_ROOT_PASSWORD
  - secretName: gymhive-rabbitmq-password
    type: Opaque
    data:
    - objectName: rabbitmq-password
      key: RABBITMQ_PASSWORD
  - secretName: gymhive-mongodb-connection
    type: Opaque
    data:
    - objectName: mongodb-connection-string
      key: MONGODB_CONNECTION_STRING
  - secretName: gymhive-auth-connection
    type: Opaque
    data:
    - objectName: auth-db-connection-string
      key: CONNECTION_STRING
  - secretName: gymhive-gym-connection
    type: Opaque
    data:
    - objectName: gym-db-connection-string
      key: CONNECTION_STRING
  - secretName: gymhive-notifications-connection
    type: Opaque
    data:
    - objectName: notifications-db-connection-string
      key: CONNECTION_STRING
  - secretName: gymhive-workout-connection
    type: Opaque
    data:
    - objectName: workout-db-connection-string
      key: CONNECTION_STRING
