apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gymhive-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/IvanPPetrov02/GymHive.git"
    targetRevision: HEAD
    path: deployment/kubernetes
    directory:
      recurse: true
      exclude:
      - gke/**
  destination:
    server: https://kubernetes.default.svc
    namespace: ""
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
