apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: gymhive
data:
  config.js: |
    window.GYMHIVE_CONFIG = {
      API_GATEWAY_URL: 'http://34.38.99.58',
      ENVIRONMENT: 'production'
    };
