apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: gymhive
data:
  config.js: |
    window.GYMHIVE_CONFIG = {
      // Use the same host the frontend is loaded from:
      // e.g. http://35.195.254.13
      API_GATEWAY_URL: window.location.origin,
      ENVIRONMENT: 'production'
    };
